version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: standalone/Dockerfile
    links:
      - node-01:node-01
      - node-02:node-02
      - node-03:node-03
    ports:
      - 80:80
  node-01:
    build: ./node
    links:
      - redis
  node-02:
    build: ./node
    links:
      - redis
  node-03:
    build: ./node
    links:
      - redis
  redis:
    image: redis